"""Map where a mission's enemies can see the player, by asking the engine.

    python tools/vismap.py <mission folder name> [--step 2] [--stand UNIT=WAYPOINT ...]

    python tools/vismap.py m01_cold_welcome --stand m01_sentry=m01_beat_barn

A stealth route cannot be designed by guessing sight lines. This builds a
scratch copy of the mission whose script moves one team member to every grid
point of the level in turn and asks the engine, for each hostile unit, whether
it sees him (UnitIsSeeUnit, the same rule the game uses). The result is a
character map of the level, written to build/vis/<mission>[_<stand>].txt:

    .   nobody sees a team member standing here
    1-9 that many hostile units see him
    #   he cannot stand here (wall, object, off the level)

Rows are y, columns are x, both in tiles from the level's corner; the map is
printed with y growing downward. The probe stands upright and unhidden, and the
light is the mission's own, so this is the worst case for the player.

--stand puts a unit on one of the mission's waypoints before scanning (for a
sentry on a patrol: scan once per point of his beat). Hostile units are those
on a player slot that the mission's [diplomacy] does not make neutral or
allied to slot 0.
"""
import argparse
import os
import re
import sys
import tomllib

import build
import config
import run as game_run
from ssdb import Database

SLOT = 990
DONE = 'VIS done'


def read_mission(source_dir, stands):
    """The mission's toml retargeted to the scratch slot, its parsed form, and its hostile unit names."""
    with open(os.path.join(source_dir, 'mission.toml'), encoding='utf-8') as f:
        text = f.read()
    spec = tomllib.loads(text)

    friendly = {0}
    for key in ('neutral', 'ally'):
        for a, b in spec.get('diplomacy', {}).get(key, []):
            if a == 0:
                friendly.add(b)
            if b == 0:
                friendly.add(a)
    hostile = [u['name'] for u in spec.get('unit', []) if u.get('player', 1) not in friendly and u.get('name')]
    if not hostile:
        sys.exit('the mission has no named hostile units to test')
    known_units = {u.get('name') for u in spec.get('unit', [])}
    known_waypoints = {w['name'] for w in spec.get('waypoint', [])}
    for unit, waypoint in stands:
        if unit not in known_units or waypoint not in known_waypoints:
            sys.exit('--stand %s=%s: no such unit or waypoint in the mission' % (unit, waypoint))

    text = re.sub(r'(?m)^slot\s*=.*$', 'slot = %d' % SLOT, text, count=1)
    text = re.sub(r'(?m)^name\s*=.*$', 'name = "vis"', text, count=1)
    return text, spec, hostile


def scan_script(hostile, stands, xs, ys):
    lines = [
        '-- generated by tools/vismap.py',
        'BeginSequence( 1 )',
        'DividedDeploy()',
        'probe = GetHero()',
    ]
    for unit, waypoint in stands:
        lines.append('UnitSetToWaypoint( GetUnit( "%s" ), "%s" )' % (unit, waypoint))
    lines.append('Sleep( 10 )')
    lines.append('function Scan()')
    lines.append('\tlocal x, y')
    lines.append('\tfor y = %d, %d, %d do' % (ys[0], ys[-1], ys[1] - ys[0]))
    lines.append('\t\tlocal row = "VIS row "..y')
    lines.append('\t\tfor x = %d, %d, %d do' % (xs[0], xs[-1], xs[1] - xs[0]))
    lines.append('\t\t\tlocal waypoint = "vis_"..x.."_"..y')
    lines.append('\t\t\tUnitSetToWaypoint( probe, waypoint )')
    lines.append('\t\t\tSleep( 1 )')
    lines.append('\t\t\tif GetDistance( GetPos( probe ), GetWaypointPos( waypoint ) ) > 1.5 then')
    lines.append('\t\t\t\trow = row.." #"')
    lines.append('\t\t\telse')
    lines.append('\t\t\t\tlocal seen = 0')
    for name in hostile:
        lines.append('\t\t\t\tif UnitIsSeeUnit( GetUnit( "%s" ), probe ) then seen = seen + 1 end' % name)
    lines.append('\t\t\t\trow = row.." "..seen')
    lines.append('\t\t\tend')
    lines.append('\t\tend')
    lines.append('\t\tout( row )')
    lines.append('\tend')
    lines.append('\tout( "%s" )' % DONE)
    lines.append('end')
    lines.append('StartThread( Scan )')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('mission', help='folder name under game/missions')
    parser.add_argument('--step', type=int, default=2, help='grid spacing in tiles (default 2)')
    parser.add_argument('--stand', action='append', default=[], metavar='UNIT=WAYPOINT',
                        help='put a unit on a waypoint before scanning (repeatable)')
    args = parser.parse_args()
    stands = [tuple(item.split('=', 1)) for item in args.stand]

    paths = config.load()
    source_dir = os.path.join(config.GAME, 'missions', args.mission)
    scratch_root = os.path.join(config.REPO, 'build', 'vis', 'game')
    scratch_dir = os.path.join(scratch_root, 'missions', 'vis')
    os.makedirs(scratch_dir, exist_ok=True)
    text, spec, hostile = read_mission(source_dir, stands)

    # the level's size is its shell template's
    db = Database.load(os.path.join(paths['run'], 'game.db.retail'))
    template = db['Templates'].get(db['TemplVariants'].get(spec['shell'])['TemplateID'])
    xs = list(range(1, template['Width'], args.step))
    ys = list(range(1, template['Height'], args.step))
    grid = ''.join('\n[[waypoint]]\nname = "vis_%d_%d"\npos = [%d.0, %d.0]\n' % (x, y, x, y)
                   for y in ys for x in xs)
    with open(os.path.join(scratch_dir, 'mission.toml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(text + grid)
    with open(os.path.join(scratch_dir, 'script.lua'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(scan_script(hostile, stands, xs, ys))

    try:
        build.build(extra=[scratch_root], skip_dialogue=True)
        party = ' '.join(str(p) for p in spec.get('party', []))
        log_path = os.path.join(config.REPO, 'build', 'vis', 'vis.log')
        result = game_run.run_game(paths['run'], 'SS2.exe', ('map %d %s' % (50000 + SLOT, party)).strip(),
                                   log_path, until=(DONE,), until_timeout=600)
    finally:
        print('restoring the normal build...', flush=True)
        build.build()
    if result.matched != DONE:
        sys.exit('the scan did not finish (see %s)' % log_path)

    rows = {}
    for line in result.log.splitlines():
        match = re.search(r'VIS row (\d+)((?: \S)+)', line)
        if match:
            rows[int(match.group(1))] = match.group(2).split()
    suffix = ''.join('_%s' % waypoint for _, waypoint in stands)
    out_path = os.path.join(config.REPO, 'build', 'vis', '%s%s.txt' % (args.mission, suffix))
    lines = ['%s: where %d hostile units see a standing team member' % (args.mission, len(hostile))]
    lines += ['stand: %s on %s' % stand for stand in stands]
    lines.append('     x ' + ''.join('%-2d' % (x % 100) if n % 2 == 0 else '  ' for n, x in enumerate(xs)))
    for y in ys:
        cells = ''.join(('.' if c == '0' else c) + ' ' for c in rows.get(y, ['?'] * len(xs)))
        lines.append('y %3d  %s' % (y, cells))
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('\n'.join(lines))
    print(out_path)


if __name__ == '__main__':
    main()
